#!/bin/bash
set -e
project=$(\
  cargo metadata \
    --format-version 1 \
    --no-deps \
  | jq -r '.packages[0].name'
  )

#
# This script is used to generate release binaries. It uses cross-rs to
# cross-compile the project to multiple architectures.
#
# If you run into any issues with linking with glibc, run `cargo clean`.
# See: https://github.com/cross-rs/cross/issues/724
#

# Install cross
cargo install cross --git https://github.com/cross-rs/cross

# Set up latest version of upx from git. The current latest release
# (v3.96-git-d7ba31cab8ce+) does not work with the binary generated by rust.
# See: https://github.com/upx/upx/issues/476
mkdir -p target
upxdir=target/.upx
upx=./$upxdir/src/upx.out

if pushd $upxdir; then git pull; popd; else git clone https://github.com/upx/upx.git $upxdir; fi
pushd $upxdir
  echo '*' > .gitignore
  git submodule update --init --recursive
  make
popd

targets=(x86_64-unknown-linux-musl aarch64-unknown-linux-musl x86_64-pc-windows-gnu)

for target in "${targets[@]}"; do
  echo "Building $project for $target"
  cross build --target $target --release

  ext=""
  if [[ $target == *"windows"* ]]; then
    ext=".exe"
  fi

  $upx target/$target/release/$project$ext
  mv target/$target/release/$project$ext target/$project-$target$ext
done

echo "Done!"
